name: diff_image
description: A package to get the difference between two images.
version: 1.0.0
homepage: https://github.com/limonadev/diff_image

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.2
  image: ^2.1.18
  meta: ^1.1.8
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.15.4
