name: diff_image
description: A package to get the difference between two images. Currently only supports images from URLs.
version: 0.1.1
homepage: https://github.com/limonadev/diff_image
author: limonadev <limonadev@whiteleaf.dev>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  image: ^2.1.18
  http: ^0.12.2
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
